create_pblock pblock_slr_0_l
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_4/inst[3].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_4/inst[0].pipe_0.u_pipe_0}]

add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/AW_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/AW_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/W_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/W_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/AR_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/AR_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/AW_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/AW_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/W_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/W_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/AR_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/AR_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/AW_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/AW_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/W_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/W_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/AR_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/AR_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_04/u_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_04/u_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/R_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/AW_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/AW_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/W_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/W_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/AW_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/AW_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/W_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/W_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/AW_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/AW_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/W_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/W_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]
resize_pblock pblock_slr_0_l -add {CLOCKREGION_X0Y0:CLOCKREGION_X3Y3}

create_pblock pblock_slr_1_l
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_4/inst[1].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_4/inst[2].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_4/inst[1].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_4/inst[2].pipe_multi.u_pipe}]

add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_1}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_2}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_3}]

add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/R_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/R_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/B_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_01/u_axi_pipe/B_pipeline/inst[2].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/R_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/R_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/B_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_02/u_axi_pipe/B_pipeline/inst[2].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/R_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/R_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/B_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_03/u_axi_pipe/B_pipeline/inst[2].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/*/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_04/u_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_04/u_pipeline/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/*/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/*/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/*/inst[2].gen_reg.reg_unit}]
resize_pblock pblock_slr_1_l -add {CLOCKREGION_X0Y4:CLOCKREGION_X3Y7}


create_pblock pblock_slr_2_l
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_4/inst[0].pipe_0.u_pipe_0}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_4/inst[3].pipe_multi.u_pipe}]

add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_4}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_5}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_6}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_7}]

add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_04/u_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_04/R_pipeline/inst[4].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/R_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/B_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_05/u_axi_pipe/B_pipeline/inst[4].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/R_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/B_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_06/u_axi_pipe/B_pipeline/inst[4].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/R_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/B_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_l [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_07/u_axi_pipe/B_pipeline/inst[4].gen_fifo.fifo_unit}]
resize_pblock pblock_slr_2_l -add {CLOCKREGION_X0Y8:CLOCKREGION_X3Y11}


create_pblock pblock_slr_0_r
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_12/inst[3].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_12/inst[0].pipe_0.u_pipe_0}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/R_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/R_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/B_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/B_pipeline/inst[2].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/AW_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/AW_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/W_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/W_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/AR_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/AR_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/AW_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/AW_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/W_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/W_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/AR_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/AR_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/AW_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/AW_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/W_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/W_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/AR_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/AR_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_12/u_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_12/u_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/R_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/AW_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/AW_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/W_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/W_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/AW_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/AW_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/W_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/W_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/AW_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/AW_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/W_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/W_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/AR_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/AR_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_0_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/B_pipeline/inst[0].gen_reg.reg_unit}]
resize_pblock pblock_slr_0_r -add {CLOCKREGION_X4Y0:CLOCKREGION_X7Y3}

create_pblock pblock_slr_1_r
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_ap_done_2/inst[0].pipe_0.u_pipe_0}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_12/inst[1].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_12/inst[2].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_12/inst[1].pipe_multi.u_pipe}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_12/inst[2].pipe_multi.u_pipe}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_control}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_9}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_10}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_11}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/AW_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/AW_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/W_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/W_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/AR_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/AR_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/R_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axil_register/B_pipeline/inst[0].gen_reg.reg_unit}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/R_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/R_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/B_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_09/u_axi_pipe/B_pipeline/inst[2].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/R_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/R_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/B_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_10/u_axi_pipe/B_pipeline/inst[2].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/R_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/R_pipeline/inst[2].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/B_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_11/u_axi_pipe/B_pipeline/inst[2].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/*/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_12/u_pipeline/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_12/u_pipeline/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/*/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/*/inst[2].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/*/inst[1].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_1_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/*/inst[2].gen_reg.reg_unit}]
resize_pblock pblock_slr_1_r -add {CLOCKREGION_X4Y4:CLOCKREGION_X7Y7}

create_pblock pblock_slr_2_r
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_start_p1_12/inst[0].pipe_0.u_pipe_0}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_wr_done_p1_12/inst[3].pipe_multi.u_pipe}]

add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_12}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_13}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_14}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_top_15}]

add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_fifo_pipe_12/u_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_rd_pipe_12/R_pipeline/inst[4].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/R_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/B_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_13/u_axi_pipe/B_pipeline/inst[4].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/R_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/B_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_14/u_axi_pipe/B_pipeline/inst[4].gen_fifo.fifo_unit}]

add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/AW_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/W_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/AR_pipeline/inst[0].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/R_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/R_pipeline/inst[4].gen_fifo.fifo_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/B_pipeline/inst[3].gen_reg.reg_unit}]
add_cells_to_pblock pblock_slr_2_r [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_axi_pipe_15/u_axi_pipe/B_pipeline/inst[4].gen_fifo.fifo_unit}]
resize_pblock pblock_slr_2_r -add {CLOCKREGION_X4Y8:CLOCKREGION_X7Y11}


create_pblock pblock_slr_0
set_property PARENT pblock_slr_0 [get_pblocks {pblock_slr_0_?}]

add_cells_to_pblock pblock_slr_0 [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_ap_done_2/inst[1].pipe_multi.u_pipe}]

add_cells_to_pblock pblock_slr_0 [get_cells -quiet -hierarchical -filter {NAME =~ pfm_top_i/dynamic_region/merge_sort_complete_1/inst/u_merge_tree_phase2_top}]
resize_pblock pblock_slr_0 -add {CLOCKREGION_X0Y0:CLOCKREGION_X7Y3}
